set nocompatible
filetype off

syntax on

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'relastle/bluewery.vim'
Plugin 'morhetz/gruvbox'
Plugin 'sainnhe/everforest'
call vundle#end()

colorscheme gruvbox
au SourcePost * highlight Normal     ctermbg=NONE guibg=NONE
	    \ | highlight LineNr     ctermbg=NONE guibg=NONE
	    \ | highlight SignColumn ctermbg=NONE guibg=NONE
	    \ | highlight NonText    ctermbg=NONE guibg=NONE

let g:airline_theme='transparent'
let g:airline_section_x = '%{&filetype}'
let g:airline_section_z = "ln:%l/%L(%p%%) col:%c"

set background=dark
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set copyindent
set smartindent
set wildmode=longest,list
set noshowmode
set nocindent
set mouse=
set background=dark
set clipboard^=unnamed,unnamedplus
if !isdirectory($HOME."/.vim/backup")
	silent! execute "!mkdir -p ~/.vim/backup"
endif
set backupdir=~/.vim/backup
set backup
set noswapfile

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

let g:haskell_indent_case = 2
let g:haskell_indent_let = 4
let g:haskell_indent_where = 6
let g:haskell_indent_before_where = 2
let g:haskell_indent_after_bare_where = 2
let g:haskell_indent_do = 3
let g:haskell_indent_in = 1
let g:haskell_indent_guard = 4
let g:haskell_indent_case_alternative = 1

filetype plugin indent on
au BufReadPre,FileReadPre *rc,*.{c,h,sh,awk} set noexpandtab ts=8 sw=8 sts=8
au BufReadPre,FileReadPre *.{hs,py,java,pl,lua} set expandtab cindent sw=4 ts=4 sts=4
au BufReadPre,FileReadPre *.{json,cc,cpp,hh,hpp,js,rb} set expandtab cindent sw=2 ts=2 sts=2

set langmap=ㅁa,ㅠb,ㅊc,ㅇd,ㄷe,ㄹf,ㅎg,ㅗh,ㅑi,ㅓj,ㅏk,ㅣl,ㅡm,ㅜn,ㅐo,ㅔp,ㅂq,ㄱr,ㄴs,ㅅt,ㅕu,ㅍv,ㅈw,ㅌx,ㅛy,ㅋz
